language: node_js

node_js: stable
cache:
  directories:
    - node_modules
    - public

before_install:
  - git config --global user.name "${gitconf_username}"
  - git config --global user.email "${gitconf_email}"

install:
  - "npm install"

script:
  #然后编辑发布线上版本
  - npm run build
  - echo "blog.zz173.com" > ./dist/CNAME
    #进入gh-pages发布逻辑
  - cd dist
  - cp index.html 404.html
  - echo "" > .gitignore
  - git init
  - git add .
  - git commit -am "publish"
  - git push --force --quiet https://${github_token}@${github_ref} master:gh-pages
  - cd ../
  - echo "everything ok!"

branches:
  only:
    - master
