# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - run: npm run build
    - run: echo "blog.zz173.com" > ./dist/CNAME
    - run: cd dist
    - run: cp index.html 404.html
    - run: echo "" > .gitignore
    - run: git init
    - run: git add .
    - run: git commit -am "publish"
    - run: git push --force --quiet https://${{github.actor}}:${{ secrets.token }}@github.com/${REPOSITORY}.git master:gh-pages
    - run: cd ../
    - run: echo "everything ok!"
